name: Node.js Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Check if frontend directory exists
      id: check_frontend
      run: |
        if [ -d "web/frontend" ]; then
          echo "frontend_exists=true" >> $GITHUB_OUTPUT
        elif [ -d "frontend" ]; then
          echo "frontend_exists=true" >> $GITHUB_OUTPUT
          echo "frontend_dir=frontend" >> $GITHUB_OUTPUT
        else
          echo "frontend_exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Install dependencies
      if: steps.check_frontend.outputs.frontend_exists == 'true'
      run: |
        FRONTEND_DIR="${{ steps.check_frontend.outputs.frontend_dir || 'web/frontend' }}"
        cd $FRONTEND_DIR
        npm ci
    
    - name: Run build
      if: steps.check_frontend.outputs.frontend_exists == 'true'
      run: |
        FRONTEND_DIR="${{ steps.check_frontend.outputs.frontend_dir || 'web/frontend' }}"
        cd $FRONTEND_DIR
        npm run build
    
    - name: Run linting
      if: steps.check_frontend.outputs.frontend_exists == 'true'
      run: |
        FRONTEND_DIR="${{ steps.check_frontend.outputs.frontend_dir || 'web/frontend' }}"
        cd $FRONTEND_DIR
        npm run lint || echo "Lint script not found, skipping"
    
    - name: No frontend found
      if: steps.check_frontend.outputs.frontend_exists == 'false'
      run: echo "No frontend directory found at web/frontend or frontend, skipping Node.js build"